### ISSUE TITLE
not showing graphs

### ISSUE THREAD

**Issue by aldrin18** [CDCgov/MIRA#18]
hello what is t he possible cause for grpahs not showing in dashboard?thank you

**Comment by nbx0** [comment]
We think we have identified the bug causing this behavior and are working on a fix! Thank you for your patience.

**Comment by kristinelacek** [comment]
@aldrin18 this behavior has been fixed with MIRA v1.1.1, you can follow the instructions to upgrade MIRA here: https://cdcgov.github.io/MIRA/articles/upgrading-mira.html

Thank you for opening this issue!
