### ISSUE TITLE
localhost port does not work

### ISSUE THREAD

**Issue by AlaseeriRawan** [CDCgov/MIRA#50]
I have downloaded everything and everything looks good on linux but when i try to browse the localhost it does not open.. says 
This page isn’t working
localhost didn’t send any data.
ERR_EMPTY_RESPONSE
any ideas on how it could work?

**Comment by kristinelacek** [comment]
hi there @AlaseeriRawan 

Can you confirm that your MIRA container is "Running" ?

If you are using docker desktop, we expect to see the containers colored green like this: https://cdcgov.github.io/MIRA/articles/running-mira.html#open-mira

**Comment by AlaseeriRawan** [comment]
I have to check again at work tomorrow but yet my mira was running and
green at the time.

**Comment by kristinelacek** [comment]
@AlaseeriRawan,  if you don't mind checking again, and emailing us a screenshot of what you see in Docker Desktop? I am happy to troubleshoot further with you over email!

idseqsupport@cdc.gov

**Comment by kristinelacek** [comment]
Hi there @AlaseeriRawan, has this been resolved?

**Comment by AlaseeriRawan** [comment]
Hi! Not really my work brought an IT guy to do it so its no longer in my
hands! Thanks though

Kind regards,
Rawan

**Comment by kristinelacek** [comment]
Thank you for the response! I will close this issue then, please feel free to reach out again if you run into any other ways we can help!
