### ISSUE TITLE
unable to download the dataset and Samplesheet

### ISSUE THREAD

**Issue by AroobAlhumaidy** [CDCgov/MIRA#71]
Hello,

I've encountered difficulties accessing certain resources to use MIRA. Specifically, I'm facing two main issues:

1. **Dataset Download Failure**: When attempting to download the dataset from the provided link ([Dataset Link](https://centersfordiseasecontrol.sharefile.com/d-s3c52c0b25c2243078f506d60bd787c62)), I consistently receive a timeout error, with the message stating that "centersfordiseasecontrol.sharefile.com took too long to respond." This issue persists despite several attempts at different times.

2. **Sample Sheet Access Issue**: Additionally, I am unable to download the sample sheet via the MIRA interface. Despite following the standard procedure for this task, there is no response from the system, and the download does not initiate or complete. It seems like there might be an underlying issue preventing access to this resource.

Given these problems, I am unable to proceed with my intended analyses. Could you please investigate these issues? I am interested to utilize your tool for my project and would appreciate any solutions you can provide to resolve these access difficulties.

Thank you for your attention to this matter. I look forward to your prompt response and any assistance you can offer.

Best,
Aroob

**Comment by kristinelacek** [comment]
Hi @AroobAlhumaidy, 
We're happy to help resolve the issues you are experiencing! 
For # 1: are you on some sort of VPN or on an internet service with a firewall? From which country are you trying to access the files? I assume you were able to install MIRA without problems so I doubt it would be related to being erroneously blocked by antivirus software...

For # 2, could you please show me how your data is organized? If the fastqs aren't in the proper location (`~/FLU_SC2_SEQUENCING/<runid_with_no_spaces>/fastq_pass/barcode##` for nanopore, or `~/FLU_SC2_SEQUENCING/<runid_with_no_spaces>/fastq` for illumina) then the samplesheet will fail to auto-create

Feel free to email us at idseqsupport@cdc.gov if you would prefer to continue via email. We appreciate any screenshots you can provide to help us solve things faster!

Best,
Kristine

**Comment by AroobAlhumaidy** [comment]
Dear Kristine,

Thank you for your prompt response. The issue has been successfully resolved, attributed to a network firewall.

I have a couple of inquiries:
- Is it possible to run the pipeline through the command line?
- Is there a possibility to export the entire report in a format similar to an RMarkdown document, such as an interactive HTML?

Thank you for your assistance.

Best,
Aroob

**Comment by kristinelacek** [comment]
Hi @AroobAlhumaidy 

I am glad you resolved the firewall issue!

For your inquiries: yes and yes

We have been working on a Command-Line version of MIRA that returns interactive .htmls--it is not yet released to public though. We expect to release it later this summer. I will be sure to notify you directly when we do.

Would you be interested in being a beta tester for MIRA-CLI?

sincerely,
Kristine

**Comment by AroobAlhumaidy** [comment]
Hello @kristinelacek 

Thank you for the updates. Yes, I'm interested. 

Best, 
Aroob

**Comment by kristinelacek** [comment]
Great! I will reach back out to you when we have the new version ready.

I will close this issue for now, please email us if you run into any more problems!

Best,
Kristine
