### ISSUE TITLE
patch submitting 

### ISSUE THREAD

**Issue by Murujit** [CDCgov/MIRA#72]
Hello 
We are using MIRA to analyze a patch of samples, but we can not submit more than 20 samples at the time ( we have more than 100 samples). Is it because we are using the developing pipeline? could this problem be solved anyway? 

Appreciate it,

**Comment by Murujit** [comment]
.

**Comment by kristinelacek** [comment]
Hello @Murujit, there is no limit to the number of samples you can run--were you able to figure out what was causing your 20 limit observation?

Please email us at idseqsupport@cdc.gov if we can help!

Sincerely,
Kristine

**Comment by Murujit** [comment]
Hello 
Yes it was solved.
Thank you for your response
