### ISSUE TITLE
Issue creating annotation and figure on Mac M2

### ISSUE THREAD

**Issue by PHemarajata** [CDCgov/MIRA#79]
I ran into this error: Run has failed during annotation and figure creation. If you need further help, please contact us at IDSeqsupport@cdc.gov

Please let me know which log files I should upload for you to look at. Thanks!

**Comment by nbx0** [comment]
Hi Peera. Thanks for reaching out! We also experience some instability with running MIRA on Mac Silicon chips and have yet to identify consistent errors that we can address unfortunately. Can you share the .apperr and .appout files that live in the directory where you create run-directories? How many samples and which module (flu/sc2 ont/illumina) are you attempting to run?

**Comment by kristinelacek** [comment]
Thanks for reaching out to us! If you need further help please feel free to email [idseqsupport@cdc.gov](mailto:idseqsupport@cdc.gov)

[MIRA v2.0.0](https://cdcgov.github.io/MIRA/articles/upgrading-mira.html) was released today and has an optional CLI-only module if that would better fit your needs!
