### ISSUE TITLE
Update repo doc style to match Influenza Division and CDC open source

### ISSUE THREAD

**Issue by leebrian** [CDCgov/MIRA#83]
This is a great project, as part of housecleaning, would you please update the repo's readme.md to match ID's open source SOP, https://flu-informatics.pages.biotech.cdc.gov/idkb/docs/sop/open_source_sop.html

**Comment by nbx0** [comment]
Thanks, @leebrian, will do. Which of yall's projects is a good example to reference in addition to IDKB?

**Comment by kristinelacek** [comment]
Merged today! https://github.com/CDCgov/MIRA?tab=readme-ov-file#public-domain-standard-notice
