### ISSUE TITLE
Sample sheet button / Run has failed

### ISSUE THREAD

**Issue by spencer411** [CDCgov/MIRA#84]
We've set up MIRA on a VM running Ubuntu 22.04.4 LTS on the Google Cloud Platform (GCP) and followed your install instructions with no problems. Our IT deptartment configured the URL to be internally accessible. We have had several issues.
 
1. We can access the URL no problem, but the DOWNLOAD SAMPLESHEET TEMPLATE button does not work.
 
2. We can make a sample sheet from scratch and select the file, but when we attempt to run MIRA using the tiny_test_run_flu_ont sequencing run (using Flu-ONT data type), we get a message that says “Run has failed. If you need further help, please contact us at IDSeqsupport@cdc.gov”
 
I have attached a screenshot here.
<img width="1142" alt="Screenshot 2024-07-30 at 12 49 12 PM" src="https://github.com/user-attachments/assets/c46aceb9-9e80-4c59-9dfb-598a6c19ec0c">

**Comment by kristinelacek** [comment]
Hi there Spencer,
Thanks for opening this issue! We have replied to your email for further collaborative troubleshooting.

Thank you!
Kristine
________________________________
From: spencer411 ***@***.***>
Sent: Tuesday, July 30, 2024 1:12 PM
To: CDCgov/MIRA ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [CDCgov/MIRA] Sample sheet button / Run has failed (Issue #84)

CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.
________________________________


We've set up MIRA on a VM running Ubuntu 22.04.4 LTS on the Google Cloud Platform (GCP) and followed your install instructions with no problems. Our IT deptartment configured the URL to be internally accessible. We have had several issues.

  1.  We can access the URL no problem, but the DOWNLOAD SAMPLESHEET TEMPLATE button does not work.

  2.  We can make a sample sheet from scratch and select the file, but when we attempt to run MIRA using the tiny_test_run_flu_ont sequencing run (using Flu-ONT data type), we get a message that says “Run has failed. If you need further help, please contact us at ***@***.******@***.***>”

I have attached a screenshot here.
Screenshot.2024-07-30.at.12.49.12.PM.png (view on web)<https://github.com/user-attachments/assets/c46aceb9-9e80-4c59-9dfb-598a6c19ec0c>

**Comment by kristinelacek** [comment]
Hi Spencer! Thanks for emailing us! If you need further help please feel free to email [idseqsupport@cdc.gov](mailto:idseqsupport@cdc.gov)

[MIRA v2.0.0](https://cdcgov.github.io/MIRA/articles/upgrading-mira.html) was released today and has an optional CLI-only module if that would better fit your needs!
