### ISSUE TITLE
Add GISAID submission guidelines to docs

### ISSUE THREAD

**Issue by nbx0** [CDCgov/MIRA#9]
Consider also adding to MIRA GUI.
[https://www.aphl.org/programs/infectious_disease/influenza/Pages/Specimen_Submission.aspx](https://www.aphl.org/programs/infectious_disease/influenza/Pages/Specimen_Submission.aspx)

**Comment by kristinelacek** [comment]
@nbx0  can you move this to GitLab? Hoping to keep issues tab reserved for users
